language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
install:
  - pip install black
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
script:
  - black --check .
  - pytest
